justatest

diff --git a/.github/workflows/run_tests_and_checks.yml b/.github/workflows/run_tests_and_checks.yml
--- a/.github/workflows/run_tests_and_checks.yml
+++ b/.github/workflows/run_tests_and_checks.yml
@@ -4,7 +4,7 @@ name: Run unittest, black and autoflake
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "main", "justatest"]
   pull_request:
     branches: [ "main" ]
 
@@ -12,42 +12,52 @@ permissions:
   contents: read
 
 jobs:
-  check:
+  # check:
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - uses: actions/checkout@v3
-    - name: Set up Python 3.10
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.10"
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #   - name: Set up Python 3.10
+  #     uses: actions/setup-python@v3
+  #     with:
+  #       python-version: "3.10"
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-        python -m pip install -U multiprocess
-        python -m pip freeze
+  #   - name: Install dependencies
+  #     run: |
+  #       python -m pip install --upgrade pip
+  #       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+  #       python -m pip install -U multiprocess
+  #       python -m pip freeze
 
-    - name: Black code style check
-      if: success() || failure()
-      uses: psf/black@stable
-      with:
-        options: "--check --diff"
-        src: "."
-        jupyter: true
-        version: "23.1.0"
+  #   - name: Black code style check
+  #     if: success() || failure()
+  #     uses: psf/black@stable
+  #     with:
+  #       options: "--check --diff"
+  #       src: "."
+  #       jupyter: true
+  #       version: "23.1.0"
   
-    - name: Unused imports and variables check
-      if: success() || failure()
-      run: |
-        python -m autoflake --remove-all-unused-imports -r . --exclude venv,archived_code -c --quiet
+  #   - name: Unused imports and variables check
+  #     if: success() || failure()
+  #     run: |
+  #       python -m autoflake --remove-all-unused-imports -r . --exclude venv,archived_code -c --quiet
 
-    - name: Run unittest
-      if: success() || failure()
-      run: |
-        python -m unittest discover
-      env:
-        NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
-        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
+  #   - name: Run unittest
+  #     if: success() || failure()
+  #     run: |
+  #       python -m unittest discover
+  #     env:
+  #       NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
+  #       WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
+
+  hello_world:
+    runs-on: ubuntu-latest
+    
+    steps:
+      - name: Say hello
+        run: echo "Hello, world!"
+      
+      - name: Heheh
+        run: touch heheh.txt
